plugins {
    id 'java'
    id "com.gradleup.shadow" version "8.3.9"
}

group = 'cn.xiaozhou233.orangex.injector'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation files("libraries/JuiceAgent-JavaInjector-1.0-SNAPSHOT.jar")
}

shadowJar {
    archiveFileName = 'Injector.jar'
    destinationDirectory = rootProject.layout.projectDirectory.dir('out')
}