[JuiceAgent]
Version = 1

[JuiceAgent.Loader]
JuiceAgentNativeLibraryPath = ""

[JuiceAgent.Modules]

[JuiceAgent.Modules.JarLoader]
Enabled = true
InjectionDir = "./injection"
JarPath = "./Loader.jar"
EntryClass = "cn.xiaozhou233.orangex.loader.Loader"
EntryMethod = "start"