/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_orangex_nativebridge_NativeBridge */

#ifndef _Included_cn_xiaozhou233_orangex_nativebridge_NativeBridge
#define _Included_cn_xiaozhou233_orangex_nativebridge_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_orangex_nativebridge_NativeBridge
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_orangex_nativebridge_NativeBridge_init
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_orangex_nativebridge_NativeBridge
 * Method:    installNUpdateHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_xiaozhou233_orangex_nativebridge_NativeBridge_installNUpdateHook
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
