plugins {
    id 'java'
    id "com.gradleup.shadow" version "8.3.9"
}

group = 'cn.xiaozhou233.orangex'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.46")
    annotationProcessor("org.projectlombok:lombok:1.18.46")

    compileOnly fileTree(dir: "../libraries", include: ["**/*.jar"])

    implementation files("../libraries/ymixin.jar")
    // https://mvnrepository.com/artifact/org.ow2.asm/asm-tree
    implementation("org.ow2.asm:asm-tree:9.8")
    // https://mvnrepository.com/artifact/org.ow2.asm/asm-tree
    implementation("org.ow2.asm:asm:9.8")
    // Source: https://mvnrepository.com/artifact/org.greenrobot/eventbus
    implementation 'org.greenrobot:eventbus:3.1.1'
    // Source: https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation 'com.google.code.gson:gson:2.13.2'
}

shadowJar {
    archiveFileName = 'OrangeX.jar'
    relocate 'org.objectweb.asm', 'cn.xiaozhou233.asm9'
    relocate 'com.google.gson', "cn.xiaozhou233.gson"
}