plugins {
    id 'java'
    id "com.gradleup.shadow" version "8.3.9"
}

group = 'cn.xiaozhou233.orangex.loader'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly files("../libraries/JuiceAgent-API-1.4.1+build.1.jar")
}

shadowJar {
    archiveFileName = 'Loader.jar'
}